DROP TABLE IF EXISTS USERENTITY CASCADE;
DROP TABLE IF EXISTS ROLEENTITY CASCADE;

CREATE TABLE ROLEENTITY (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY ,
    name VARCHAR(32) unique,
    primary key (id)
);

CREATE TABLE USERENTITY (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    birthday DATE,
    email VARCHAR(32) unique,
    firstName VARCHAR(32),
    lastName VARCHAR(32),
    login VARCHAR(32) unique,
    password VARCHAR(100),
    roleEntity_id INTEGER,
    PRIMARY KEY (id),
    FOREIGN KEY (roleEntity_id) REFERENCES ROLEENTITY
);

INSERT INTO ROLEENTITY (id, name) values (default, 'ADMIN');
INSERT INTO ROLEENTITY (id, name) values (default, 'USER');

INSERT INTO USERENTITY (id, birthday, email, firstName, lastName, login, password, roleEntity_id)
VALUES (default, '2010-01-01', 'emailAdmin@gmail.com', 'Bohdan', 'Koval', 'admin', '$2a$12$J9cUMHWgREfgm/KYyvbug.zthJu1rq0L/N9G.DXXXWJjdq4pyxn1y', 1);

INSERT INTO USERENTITY (id, birthday, email, firstName, lastName, login, password, roleEntity_id)
VALUES (default,'2010-01-01', 'emailUser@gmail.com', 'NeBohdan', 'NeKoval', 'user', '$2a$12$4mzYUggiLflK82KMK5yB4uwO5BUj.pCTVoIBdtmEq.OtY9VmvRuSa', 2);