drop table if exists USERENTITY;
drop table if exists roleEntity;

CREATE TABLE IF NOT EXISTS roleEntity
(
    id IDENTITY,
    name VARCHAR(256) NOT NULL UNIQUE
);

insert into roleEntity (id, name) values (default, 'ADMIN');
insert into roleEntity (id, name) values (default, 'USER');

create table USERENTITY (id integer generated by default as identity,
birthday date,
email varchar(32),
firstName varchar(32),
lastName varchar(32),
login varchar(32),
password varchar(32),
role_id integer, primary key (id));